"""FeatureMatch diagnosis, STEP 2: style-robustness filter (the main validity fix; PLAN.md STEP 2 + STEP 1b).

Plain language: the original answer key says "latent j belongs to concept c*" because j separates c*'s
encyclopedia-style dataset texts (split A) from every other concept's. If j only does that on encyclopedia-style
text and goes quiet on a casual post or a dialogue about c*, an agent that writes its own probes in another style
sees nothing, and fails for a reason that has nothing to do with interpretability. This module re-derives the key on
a MULTI-STYLE text set (PREREG Amendment 1, A1.1, binding) and keeps only the pooled LATENTS whose key survives:

  c*    = argmax over all concepts of AUROC_A (the generator's anchor = the original key)
  k_ms  = argmax over all concepts of M(c) = 0.5 AUROC_A(c) + 0.5 AUROC_F1(c)       (equal weight, separate sets)
  k_ho  = argmax over all concepts of H(c) = 0.5 AUROC_C(c) + 0.5 AUROC_F2(c)       (H = AUROC_F2 without split C)
  style-robust iff AUROC_F2(c*) >= 0.85 AND AUROC_C(c*) >= 0.85                       (two separate thresholds)
  keep iff k_ms == c* and k_ho == c* and style-robust; the rule acts on latents, identically for planted and null use
  F1/F2: for each concept and style, the FIRST text listed in the bank-F file is F1, the second F2.
The filtered pool is then REGENERATED by generator v2 from the kept latents only (write_v2f.py).
AUROC is exactly the generator's (auroc.auroc_table): concept-vs-rest over the whole 232-concept universe, ties 1/2.

Modes
  compute   (GPU, one gpuq job) gemma-2-2b + the 3 cached Gemma Scope SAEs over every bank-F and bank-R text, with the
            generator's per-text summary (fm_core.Subject.maxpool_acts: max over tokens, BOS excluded, texts truncated
            to MAX_TOKENS=64 tokens; texts whitespace-normalised and cut to 400 chars exactly like concepts.py).
            Writes diagnosis/cache/bank_acts_L{6,12,18}_{F,R}.npy float16 [4640, 16384] (gitignored) + bank_meta.json +
            manifest.json (shapes, sha256); the manifest is also copied to diagnosis/style_filter_cache_manifest.json.
            --dry-run: CPU, 2 concepts, 1 layer, output under diagnosis/cache/dryrun/.
  analyze   (CPU) A1.1 verdict for every latent of generator v2's pool, the consequences for every slot of the current
            v2 pool, survivor-vs-dropped comparison. Writes diagnosis/key_check.jsonl, diagnosis/slot_disagreements.jsonl
            (both committed), diagnosis/style_filter_out/{pool_latents.csv,slots.csv,summary.json} and
            diagnosis/cache/pool_scores.npz (M, H, AUROC_C, AUROC_F2 rows of every pooled latent; used by write_v2f.py).
            Memory: one layer at a time, memory-mapped activations, only pooled columns, float32.

Usage (from ~/wt/fmdiag, after `source ~/ideating-rl-tests/common/env.sh`): see diagnosis/STYLE_FILTER.md.
"""
import argparse
import csv
import glob
import hashlib
import json
import os
import subprocess
import sys
import time
from collections import Counter, defaultdict

import numpy as np

from tasks.featurematch import concepts as C
from tasks.featurematch.auroc import auroc_table
from tasks.featurematch.fm_core import D_SAE, LAYERS, MAX_TOKENS

HERE = os.path.dirname(os.path.abspath(__file__))
TASK = os.path.dirname(HERE)
BANKS = os.path.join(HERE, "banks")
DIAG_CACHE = os.path.join(HERE, "cache")
OUT = os.path.join(HERE, "style_filter_out")
REPO_MANIFEST = os.path.join(HERE, "style_filter_cache_manifest.json")
FM_MAIN = os.path.expanduser("~/wt/featurematch/tasks/featurematch")   # read-only: v2 caches + instances live here
THR = 0.85
BATCH = 32                  # same as precompute.py
SPLIT_SEED = 20261002       # legacy (pre-A1.1 random F1/F2 split); only recorded in bank_meta by compute
GPU_LABEL = "featurematch-diag-banks"
FEATS = ["generic_fire_A", "generic_fire_F", "fire_A_anchor", "fire_F_anchor", "margin_A", "margin_C", "margin_F2",
         "auroc_A_anchor", "auroc_C_anchor", "auroc_F2_anchor"]


# ---------------------------------------------------------------------------------------------------------- paths
def default_src_cache():
    """Where the v2 generator's caches live (concepts.json, precompute_meta.json, acts/auroc tables). They are
    gitignored, so this worktree has none; the fix-stage worktree's copy is read (never written)."""
    if os.environ.get("FM_SRC_CACHE"):
        return os.environ["FM_SRC_CACHE"]
    local = os.path.join(TASK, "cache")
    return local if os.path.exists(os.path.join(local, "precompute_meta.json")) else os.path.join(FM_MAIN, "cache")


def default_src_instances():
    return os.environ.get("FM_SRC_INSTANCES") or os.path.join(FM_MAIN, "instances")


def use_src_cache(src_cache):
    """Point concepts.py (and through it generate.Tables / simulate.load) at src_cache. Module-global patch, so call it
    once per process before building Tables."""
    C.CACHE = src_cache
    C.OUT = os.path.join(src_cache, "concepts.json")


def load_tables(src_cache):
    use_src_cache(src_cache)
    from tasks.featurematch.generate import Tables
    return Tables()


def sha256_file(p, buf=1 << 22):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        while True:
            b = f.read(buf)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def git_sha():
    try:
        return subprocess.run(["git", "-C", HERE, "rev-parse", "HEAD"], capture_output=True, text=True).stdout.strip()
    except Exception:
        return None


def norm_text(t):
    """Exactly the normalisation concepts.py applied to the dataset texts (whitespace collapse, 400 chars)."""
    return " ".join(str(t).split())[:C.MAX_CHARS]


# ----------------------------------------------------------------------------------------------------------- banks
def load_bank(bank, banks_dir, cids, concept_idx=None):
    """Rows of one bank in the generator's concept order. Returns texts, rows (index into cids), styles."""
    allc = {}
    files = sorted(glob.glob(os.path.join(banks_dir, bank, "chunk_*.json")))
    if not files:
        raise FileNotFoundError(f"no bank {bank} chunks under {banks_dir}")
    for f in files:
        d = json.load(open(f))
        if d.get("bank") not in (None, bank):
            raise ValueError(f"{f}: bank field {d.get('bank')!r} != {bank!r}")
        dup = set(allc) & set(d["concepts"])
        if dup:
            raise ValueError(f"{f}: concepts repeated across chunks: {sorted(dup)[:3]}")
        allc.update(d["concepts"])
    idx = range(len(cids)) if concept_idx is None else concept_idx
    missing = [cids[i] for i in idx if cids[i] not in allc]
    if missing:
        raise ValueError(f"bank {bank} lacks {len(missing)} concepts, e.g. {missing[:3]}")
    texts, rows, styles = [], [], []
    for i in idx:
        for t in allc[cids[i]]:
            texts.append(norm_text(t["text"]))
            rows.append(int(i))
            styles.append(t["style"])
    return texts, rows, styles


# --------------------------------------------------------------------------------------------------------- compute
def compute(subject, src_cache=None, banks_dir=BANKS, out_dir=DIAG_CACHE, banks=("F", "R"), layers=LAYERS,
            concept_idx=None, batch=BATCH, consistency_n=32, repo_manifest=None, extra_meta=None, log=print):
    """Run `subject.maxpool_acts` (fm_core.Subject or a stub with the same signature) over the banks.
    Rows keep the generator's concept order (precompute_meta cids). Writes float16 arrays + bank_meta + manifest."""
    t0 = time.time()
    src_cache = src_cache or default_src_cache()
    meta = json.load(open(os.path.join(src_cache, "precompute_meta.json")))
    cids = meta["cids"]
    os.makedirs(out_dir, exist_ok=True)
    bmeta = {"cids": cids, "layers": list(layers), "max_tokens": MAX_TOKENS, "max_chars": C.MAX_CHARS,
             "batch": batch, "summary": "max over tokens excluding BOS (fm_core.Subject.maxpool_acts)",
             "split_seed": SPLIT_SEED, "banks": {}}
    files = {}
    for bank in banks:
        texts, rows, styles = load_bank(bank, banks_dir, cids, concept_idx)
        acts = {L: np.zeros((len(texts), D_SAE), dtype=np.float16) for L in layers}
        nb = (len(texts) + batch - 1) // batch
        for b, i in enumerate(range(0, len(texts), batch)):
            r = subject.maxpool_acts(texts[i:i + batch], layers=tuple(layers))
            for L in layers:
                a = np.asarray(r[L])
                if a.shape != (len(texts[i:i + batch]), D_SAE):
                    raise ValueError(f"subject returned shape {a.shape} for layer {L}")
                acts[L][i:i + len(a)] = a.astype(np.float16)
            if (b + 1) % 20 == 0 or b + 1 == nb:
                log(f"bank {bank}: batch {b + 1}/{nb} ({time.time() - t0:.0f}s)")
        for L in layers:
            p = os.path.join(out_dir, f"bank_acts_L{L}_{bank}.npy")
            np.save(p + ".tmp.npy", acts[L])
            os.replace(p + ".tmp.npy", p)
            files[os.path.basename(p)] = p
        bmeta["banks"][bank] = {"n": len(texts), "rows": rows, "styles": styles,
                                "texts_sha256": hashlib.sha256("\n".join(texts).encode()).hexdigest(),
                                "per_text_sha256": [hashlib.sha256(t.encode()).hexdigest()[:16] for t in texts]}
        del acts
    # consistency with the generator's cache: re-run split-A batch 0 (concept 0's first texts, exactly precompute's
    # first batch when consistency_n == 32) and compare with acts_L*_A.npy rows. Same device/dtype => identical.
    cons = {}
    if consistency_n:
        use_src_cache(src_cache)
        cs = C.load()
        A = [t for c in cs for t in c["A"]][:consistency_n]
        r = subject.maxpool_acts(A, layers=tuple(layers))
        for L in layers:
            ref = np.load(os.path.join(src_cache, f"acts_L{L}_A.npy"), mmap_mode="r")[:len(A)].astype(np.float32)
            got = np.asarray(r[L]).astype(np.float16).astype(np.float32)
            d = np.abs(got - ref)
            both, either = (got > 0) & (ref > 0), (got > 0) | (ref > 0)
            rel = d[both] / np.abs(ref[both]) if both.any() else np.zeros(1)
            cons[f"L{L}"] = {"n_texts": len(A), "max_abs_diff": float(d.max()),
                             "frac_entries_equal": float((d == 0).mean()),
                             "frac_active_entries_equal": float((d[either] == 0).mean()) if either.any() else 1.0,
                             "jaccard_active_sets": float(both.sum() / max(1, either.sum())),
                             "median_rel_diff_both_active": float(np.median(rel)),
                             "pearson_r": float(np.corrcoef(got.ravel(), ref.ravel())[0, 1])
                             if got.std() > 0 and ref.std() > 0 else None,
                             "max_activation_ref": float(ref.max())}
        log("consistency vs generator cache: " + json.dumps(cons))
    bmeta["consistency_vs_acts_A"] = cons
    bmeta["elapsed_s"] = round(time.time() - t0, 1)
    bmeta.update(extra_meta or {})
    mp = os.path.join(out_dir, "bank_meta.json")
    json.dump(bmeta, open(mp, "w"))
    files["bank_meta.json"] = mp
    man = {"what": "FeatureMatch diagnosis step 2: max-pooled SAE activations of bank F/R texts",
           "generator_summary": "tasks/featurematch/fm_core.py Subject.maxpool_acts", "git_sha": git_sha(),
           "src_cache": src_cache, "consistency_vs_acts_A": cons, "elapsed_s": bmeta["elapsed_s"],
           "files": {}}
    for name, p in sorted(files.items()):
        ent = {"bytes": os.path.getsize(p), "sha256": sha256_file(p)}
        if p.endswith(".npy"):
            a = np.load(p, mmap_mode="r")
            ent.update({"shape": list(a.shape), "dtype": str(a.dtype)})
        man["files"][name] = ent
    man.update(extra_meta or {})
    json.dump(man, open(os.path.join(out_dir, "manifest.json"), "w"), indent=1)
    if repo_manifest:
        json.dump(man, open(repo_manifest, "w"), indent=1)
    log(f"compute done in {time.time() - t0:.0f}s -> {out_dir}")
    return man


def run_compute(a):
    import torch
    from common import gpuq
    gpuq.apply_caps()
    from tasks.featurematch.fm_core import Subject, model_path, sae_path
    src_cache = a.src_cache or default_src_cache()
    cids = json.load(open(os.path.join(src_cache, "precompute_meta.json")))["cids"]
    if a.dry_run:
        layers = (int(a.layers.split(",")[0]) if a.layers else 12,)
        first_topic = next(i for i, c in enumerate(cids) if c.startswith("topic:"))
        concept_idx = [0, first_topic]           # one language concept + one topic concept
        out_dir = a.out_dir or os.path.join(DIAG_CACHE, "dryrun")
        device = a.device or "cpu"
        consistency_n = a.consistency_n if a.consistency_n is not None else 2
        repo_manifest = None
    else:
        layers = tuple(int(x) for x in a.layers.split(",")) if a.layers else LAYERS
        concept_idx = None
        out_dir = a.out_dir or DIAG_CACHE
        device = a.device
        consistency_n = a.consistency_n if a.consistency_n is not None else 32
        repo_manifest = REPO_MANIFEST if out_dir == DIAG_CACHE else None
    # disk preflight BEFORE taking the GPU: float16 [n_texts, 16384] per layer and bank, written via a temp file
    n_texts = (len(concept_idx) if concept_idx is not None else len(cids)) * 20
    need = int(n_texts * D_SAE * 2 * len(layers) * len(a.banks.split(",")) * 1.1) + (64 << 20)
    os.makedirs(out_dir, exist_ok=True)
    st = os.statvfs(out_dir)
    free = st.f_bavail * st.f_frsize
    if free < need:
        sys.exit(f"not enough disk for the outputs: need ~{need / 1e9:.2f} GB under {out_dir}, "
                 f"free {free / 1e9:.2f} GB. Free space first (nothing was computed).")
    t0 = time.time()
    subj = Subject(device=device, layers=layers, load_decoder=False)
    print(f"model loaded on {subj.device} in {time.time() - t0:.0f}s (layers {layers})", flush=True)
    extra = {"dry_run": bool(a.dry_run), "device": str(subj.device), "torch": torch.__version__,
             "model_path": os.path.relpath(model_path(), TASK) if os.path.isabs(model_path()) else model_path(),
             "sae": {f"L{L}": sae_path(L).split("snapshots/")[-1] for L in layers}}
    if concept_idx is not None:
        extra["concepts"] = [cids[i] for i in concept_idx]
    compute(subj, src_cache=src_cache, banks_dir=a.banks_dir, out_dir=out_dir, banks=tuple(a.banks.split(",")),
            layers=layers, concept_idx=concept_idx, batch=a.batch, consistency_n=consistency_n,
            repo_manifest=repo_manifest, extra_meta=extra, log=lambda s: print(s, flush=True))


# ---------------------------------------------------------------------------------------- analyze (PREREG A1.1)
def scores(aA, aC, aF1, aF2):
    """PREREG Amendment 1, A1.1, over ALL concepts (last axis = concept index; AUROC rows of one latent or a stack).
    M(c) = 0.5 x AUROC_A(c) + 0.5 x AUROC_F1(c): dataset text and styled text get EQUAL weight (each AUROC is
           computed within its own text set; A and F1 are never pooled into one text set).
    H(c) = 0.5 x AUROC_C(c) + 0.5 x AUROC_F2(c); for a concept without split C (AUROC_C is NaN) H(c) = AUROC_F2(c)."""
    aA, aC, aF1, aF2 = (np.asarray(x, dtype=np.float64) for x in (aA, aC, aF1, aF2))
    M = 0.5 * aA + 0.5 * aF1
    H = np.where(np.isfinite(aC), 0.5 * aC + 0.5 * aF2, aF2)
    return M, H


def _argmax(x):
    """argmax with NaN treated as -inf (a concept without texts in a set never wins)."""
    x = np.where(np.isfinite(x), x, -np.inf)
    return int(np.argmax(x))


def _top(x, k=3):
    x = np.where(np.isfinite(x), x, -np.inf)
    idx = np.argsort(-x, kind="stable")[:k]
    return [(int(i), float(x[i])) for i in idx]


def verdict(cstar, aA, aC, aF1, aF2, thr=THR):
    """The A1.1 keep rule for ONE pooled latent with original key c* (= argmax AUROC_A, the generator's anchor).
    Acts on the latent, so it is the same whether the latent later sits in a planted or a null slot.
      k_ms = argmax over all concepts of M;  k_ho = argmax over all concepts of H
      style-robust iff AUROC_F2(c*) >= thr AND AUROC_C(c*) >= thr (two separate thresholds)
      keep iff k_ms == c* and k_ho == c* and style-robust
    Reasons (several allowed): ms_key_differs, heldout_key_differs, not_style_robust."""
    cstar = int(cstar)
    M, H = scores(aA, aC, aF1, aF2)
    k_ms, k_ho = _argmax(M), _argmax(H)
    f2, c = float(aF2[cstar]), float(aC[cstar])
    rob_f2 = bool(np.isfinite(f2) and f2 >= thr)
    rob_c = bool(np.isfinite(c) and c >= thr)
    reasons = []
    if k_ms != cstar:
        reasons.append("ms_key_differs")
    if k_ho != cstar:
        reasons.append("heldout_key_differs")
    if not (rob_f2 and rob_c):
        reasons.append("not_style_robust")
    Mf, Hf = np.where(np.isfinite(M), M, -np.inf), np.where(np.isfinite(H), H, -np.inf)
    return {"k_ms": k_ms, "k_ho": k_ho, "robust_F2": rob_f2, "robust_C": rob_c, "robust": rob_f2 and rob_c,
            "keep": not reasons, "reasons": reasons, "M": M, "H": H,
            "tie_ms": bool((Mf == Mf.max()).sum() > 1), "tie_ho": bool((Hf == Hf.max()).sum() > 1)}


def option_pick(k, menu):
    """1-based option number of concept k on the menu, or 'not on menu'."""
    menu = [int(c) for c in menu]
    return menu.index(int(k)) + 1 if int(k) in menu else "not on menu"


def split_f1(rows, styles):
    """PREREG A1.1 (fixed before any bank activation existed): for each concept and each of its styles, the FIRST text
    listed for that style in the bank-F file goes to F1, the SECOND to F2. `rows`/`styles` are in bank-file order
    (load_bank keeps it; analyze verifies it against the files). Returns a boolean mask, True = F1."""
    seen = Counter()
    mask = np.zeros(len(rows), dtype=bool)
    for i, (r, s) in enumerate(zip(rows, styles)):
        key = (int(r), s)
        mask[i] = seen[key] == 0
        seen[key] += 1
    bad = {k: v for k, v in seen.items() if v != 2}
    if bad:
        raise ValueError(f"A1.1 needs exactly 2 bank-F texts per (concept, style); got e.g. {list(bad.items())[:3]}")
    return mask


def check_bank_order(bmeta, banks_dir, cids):
    """bank_meta's F rows must be the bank-F files in file order (so 'first listed' is well defined)."""
    texts, rows, styles = load_bank("F", banks_dir, cids)
    fb = bmeta["banks"]["F"]
    h = [hashlib.sha256(t.encode()).hexdigest()[:16] for t in texts]
    if rows != fb["rows"] or styles != fb["styles"] or h != fb["per_text_sha256"]:
        raise ValueError("bank_meta F rows/styles/texts differ from the bank-F files: recompute the bank activations")
    return len(texts)


class LayerStats:
    """AUROC tables [k, n_c] of the selected latents (columns) of ONE layer on A, C, F (all of bank F), F1, F2.
    Memory: activations are memory-mapped and only the k selected columns are read, as float32."""

    SETS = ("A", "C", "F", "F1", "F2")

    def __init__(self, L, cols, src_cache, diag_cache, meta, bmeta, f1, n_c):
        self.L = L
        self.cols = np.array(sorted(set(int(c) for c in cols)), dtype=np.int64)
        self.pos = {int(j): i for i, j in enumerate(self.cols)}
        ld = lambda p: np.asarray(np.load(p, mmap_mode="r")[:, self.cols], dtype=np.float32)   # noqa: E731
        XA = ld(os.path.join(src_cache, f"acts_L{L}_A.npy"))
        XC = ld(os.path.join(src_cache, f"acts_L{L}_C.npy"))
        XF = ld(os.path.join(diag_cache, f"bank_acts_L{L}_F.npy"))
        rA, rC = np.asarray(meta["rowsA"]), np.asarray(meta["rowsC"])
        rF = np.asarray(bmeta["banks"]["F"]["rows"])
        if len(rF) != len(XF):
            raise ValueError(f"bank F acts rows {len(XF)} != bank_meta rows {len(rF)}")
        data = {"A": (XA, rA), "C": (XC, rC), "F": (XF, rF), "F1": (XF[f1], rF[f1]), "F2": (XF[~f1], rF[~f1])}
        self.au = {}
        with np.errstate(divide="ignore", invalid="ignore"):
            for s in self.SETS:
                X, r = data[s]
                self.au[s] = auroc_table(X, r, n_c) if len(self.cols) else np.zeros((0, n_c), np.float32)
        self.fire_F = self._fire(XF, rF, n_c)
        self.fire_A = self._fire(XA, rA, n_c)
        self.gen_fire_F = (XF > 0).mean(0)
        del XA, XC, XF, data
        # integrity check: split-A AUROC must reproduce the generator's cached table (float16-rounded)
        cached = np.load(os.path.join(src_cache, f"auroc_L{L}_A.npy"), mmap_mode="r")[self.cols].astype(np.float32)
        self.max_diff_vs_cached_A = float(np.nanmax(np.abs(self.au["A"] - cached))) if len(self.cols) else 0.0
        if self.max_diff_vs_cached_A > 2e-3:
            raise RuntimeError(f"L{L}: split-A AUROC differs from the generator cache by {self.max_diff_vs_cached_A}; "
                               "rows/columns misaligned or a different cache")

    @staticmethod
    def _fire(X, rows, n_c):
        f = np.zeros((n_c, X.shape[1]), dtype=np.float64)
        np.add.at(f, rows, (X > 0).astype(np.float64))
        cnt = np.bincount(rows, minlength=n_c)[:, None]
        with np.errstate(divide="ignore", invalid="ignore"):
            return (f / cnt).T          # [k, n_c], nan for concepts without texts in X

    def row(self, s, j):
        return self.au[s][self.pos[int(j)]]


def _f(x, nd=4):
    if x is None:
        return None
    x = float(x)
    return None if not np.isfinite(x) else round(x, nd)


def describe(vals):
    a = np.array([v for v in vals if v is not None and np.isfinite(v)], dtype=np.float64)
    if not len(a):
        return {"n": 0}
    return {"n": int(len(a)), "median": _f(np.median(a)), "mean": _f(a.mean()), "q25": _f(np.percentile(a, 25)),
            "q75": _f(np.percentile(a, 75))}


def compare(rows, flag="keep", feats=FEATS):
    """Survivors vs dropped: per-feature distribution, Mann-Whitney p, median difference / ratio, and mixes."""
    from scipy.stats import mannwhitneyu
    g = {True: [r for r in rows if r[flag]], False: [r for r in rows if not r[flag]]}
    out = {"n_kept": len(g[True]), "n_dropped": len(g[False]), "features": {}}
    for f in feats:
        k = [r.get(f) for r in g[True]]
        d = [r.get(f) for r in g[False]]
        dk, dd = describe(k), describe(d)
        ent = {"kept": dk, "dropped": dd}
        if dk["n"] and dd["n"]:
            ka = [x for x in k if x is not None and np.isfinite(x)]
            da = [x for x in d if x is not None and np.isfinite(x)]
            try:
                ent["mannwhitney_p"] = _f(mannwhitneyu(ka, da).pvalue, 5)
            except ValueError:
                ent["mannwhitney_p"] = None
            ent["median_diff_kept_minus_dropped"] = _f(dk["median"] - dd["median"])
            ent["median_ratio_kept_over_dropped"] = _f(dk["median"] / dd["median"]) if dd["median"] else None
        out["features"][f] = ent
    for key in ("layer", "family", "kind", "tier"):
        if rows and key in rows[0]:
            out[f"{key}_mix"] = {str(v): {"kept": sum(1 for r in g[True] if r[key] == v),
                                         "dropped": sum(1 for r in g[False] if r[key] == v)}
                                 for v in sorted({r[key] for r in rows}, key=str)}
    return out


def easier_verdict(cmp_, ref=None):
    """PREREG step 2: 'the filter selects easier latents' if survivors' median margin_C exceeds the dropped
    latents' by > 0.05, OR survivors' median generic fire rate is > 1.25x the dropped latents', OR reference planted
    accuracy on survivors exceeds that on dropped by > 0.05."""
    f = cmp_["features"]
    md = f.get("margin_C", {}).get("median_diff_kept_minus_dropped")
    dr = f.get("generic_fire_A", {}).get("median_ratio_kept_over_dropped")
    parts = {"margin_C_median_diff": md, "margin_C_gt_0.05": None if md is None else md > 0.05,
             "density_median_ratio": dr, "density_ratio_gt_1.25": None if dr is None else dr > 1.25}
    if ref:
        parts.update({k: v for k, v in ref.items() if k.startswith("ref_")})
        rd = ref.get("ref_planted_acc_kept_minus_dropped")
        parts["ref_acc_gt_0.05"] = None if rd is None else rd > 0.05
    flags = [v for k, v in parts.items() if k.endswith(("gt_0.05", "gt_1.25")) and v is not None]
    parts["filter_selects_easier"] = bool(any(flags)) if flags else None
    return parts


def iter_instances(inst_dir):
    for d in sorted(glob.glob(os.path.join(inst_dir, "*"))):
        p = os.path.join(d, "instance.json")
        if os.path.exists(p):
            yield d, json.load(open(p))


def analyze(src_cache=None, src_instances=None, diag_cache=DIAG_CACHE, out_dir=OUT, thr=THR, ref_sims=1,
            banks_dir=BANKS, logs_dir=HERE, log=print):
    """PREREG A1.1 step 2 on CPU: per pooled latent verdicts (key_check.jsonl), per current-v2-slot consequences
    (slot_disagreements.jsonl), survivor-vs-dropped comparison, summary. One layer at a time; only pooled columns."""
    t0 = time.time()
    src_cache = src_cache or default_src_cache()
    src_instances = src_instances or default_src_instances()
    os.makedirs(out_dir, exist_ok=True)
    meta = json.load(open(os.path.join(src_cache, "precompute_meta.json")))
    bmeta = json.load(open(os.path.join(diag_cache, "bank_meta.json")))
    if bmeta["cids"] != meta["cids"]:
        raise ValueError("bank_meta concept order differs from the generator cache")
    cids = meta["cids"]
    n_c = len(cids)
    cid2i = {c: i for i, c in enumerate(cids)}
    fb = bmeta["banks"]["F"]
    if len(set(fb["rows"])) != n_c:
        raise ValueError(f"bank F covers {len(set(fb['rows']))} of {n_c} concepts (dry-run output?)")
    n_bank_checked = check_bank_order(bmeta, banks_dir, cids) if banks_dir else None
    f1 = split_f1(fb["rows"], fb["styles"])
    insts = list(iter_instances(src_instances))
    if not insts:
        raise FileNotFoundError(f"no instances under {src_instances}")
    T = load_tables(src_cache)
    fam = lambda c: cids[c].split(":")[0]           # noqa: E731  "lang" or "topic"
    pool_set = {L: {j for j, _ in T.planted[L]} for L in LAYERS}
    for _, inst in insts:
        for s in inst["extra"]["slots"]:
            if int(s["real_latent"]) not in pool_set[int(s["layer"])]:
                raise RuntimeError(f"{inst['instance_id']}: slot latent not in the generator pool (other cache?)")

    key_rows, pool_rows, slot_rows, npz = [], [], [], {}
    integ = {}
    max_menu_diff = 0.0
    n_a32_reorder = 0
    lat_v = {}
    for L in LAYERS:
        tl = time.time()
        st = LayerStats(L, pool_set[L], src_cache, diag_cache, meta, bmeta, f1, n_c)
        integ[f"L{L}"] = _f(st.max_diff_vs_cached_A, 6)
        ans = np.array(T.answerable[L])
        rate = T.rate[L]
        Ms, Hs, ids = [], [], []
        for j, c in T.planted[L]:
            a = {k: st.row(k, j) for k in st.SETS}
            # AUROC_A is the generator's own cached table (float16-rounded), so c* = argmax AUROC_A is EXACTLY the
            # generator's anchor; the float32 recomputation agrees within 2e-3 but can reorder near-ties.
            if _argmax(a["A"]) != c:
                n_a32_reorder += 1
            a["A"] = T.aA[L][j].astype(np.float32)
            assert _argmax(a["A"]) == c
            v = verdict(c, a["A"], a["C"], a["F1"], a["F2"], thr)
            lat_v[(L, j)] = v
            others = ans[ans != c]
            M, H = v["M"], v["H"]
            om = lambda arr: float(arr[c] - np.nanmax(np.delete(arr, c)))       # noqa: E731  vs all other concepts
            key_rows.append({
                "layer": L, "real_latent": int(j), "c_star": cids[c], "family": fam(c),
                "k_ms": cids[v["k_ms"]], "k_ho": cids[v["k_ho"]],
                "top3_A": [[cids[i], _f(x)] for i, x in _top(a["A"])],
                "top3_M": [[cids[i], _f(x)] for i, x in _top(M)],
                "top3_H": [[cids[i], _f(x)] for i, x in _top(H)],
                "auroc_C_cstar": _f(a["C"][c]), "auroc_F1_cstar": _f(a["F1"][c]), "auroc_F2_cstar": _f(a["F2"][c]),
                "kept": v["keep"], "reasons": v["reasons"]})
            pool_rows.append({
                "layer": L, "real_latent": int(j), "anchor": cids[c], "family": fam(c), "keep": v["keep"],
                "reasons": "+".join(v["reasons"]), "ms_ok": v["k_ms"] == c, "ho_ok": v["k_ho"] == c,
                "robust": v["robust"], "robust_F2": v["robust_F2"], "robust_C": v["robust_C"],
                "robust_F_all (PREREG auroc_F)": bool(a["F"][c] >= thr),
                "tie_ms": v["tie_ms"], "tie_ho": v["tie_ho"],
                "auroc_A_anchor": _f(a["A"][c]), "auroc_B_anchor": _f(T.aB[L][j, c]), "auroc_C_anchor": _f(a["C"][c]),
                "auroc_F_anchor": _f(a["F"][c]), "auroc_F1_anchor": _f(a["F1"][c]), "auroc_F2_anchor": _f(a["F2"][c]),
                "M_margin": _f(om(M)), "H_margin": _f(om(H)), "k_ms": cids[v["k_ms"]], "k_ho": cids[v["k_ho"]],
                "margin_A": _f(a["A"][c] - np.nanmax(a["A"][others])),
                "margin_B": _f(T.aB[L][j, c] - np.nanmax(T.aB[L][j][others])),
                "margin_C": _f(a["C"][c] - np.nanmax(a["C"][others])),
                "fire_A_anchor": _f(st.fire_A[st.pos[j], c]), "fire_F_anchor": _f(st.fire_F[st.pos[j], c]),
                "generic_fire_A": _f(rate[j]), "generic_fire_F": _f(st.gen_fire_F[st.pos[j]])})
            ids.append(j)
            Ms.append(M.astype(np.float32))
            Hs.append(H.astype(np.float32))
        npz[f"L{L}_latents"] = np.array(ids, dtype=np.int64)
        npz[f"L{L}_M"] = np.array(Ms, dtype=np.float32).reshape(len(ids), n_c)
        npz[f"L{L}_H"] = np.array(Hs, dtype=np.float32).reshape(len(ids), n_c)
        for s_ in ("C", "F2"):
            npz[f"L{L}_{s_}"] = np.array([st.row(s_, j) for j in ids], dtype=np.float32).reshape(len(ids), n_c)
        # ---- current v2 slots at this layer
        for _, inst in insts:
            for si, s in enumerate(inst["extra"]["slots"]):
                if int(s["layer"]) != L:
                    continue
                j = int(s["real_latent"])
                v = lat_v[(L, j)]
                kind = "planted" if s["kind"] == "planted" else "null"
                anchor = cid2i[s["anchor"]]
                menu = [cid2i[c] for c in s["menu"]]
                a = {k: st.row(k, j) for k in ("A", "C", "F2")}
                max_menu_diff = max(max_menu_diff, float(np.max(np.abs(np.array(s["menu_auroc_A"]) - a["A"][menu]))))
                others = [c for c in menu if c != anchor]
                mg = lambda arr: float(arr[anchor] - np.nanmax(arr[others]))     # noqa: E731
                M = v["M"]
                ms_menu = menu[_argmax(M[menu])]
                slot_rows.append({
                    "instance_id": inst["instance_id"], "tier": inst["tier"], "slot": si, "kind": kind, "layer": L,
                    "real_latent": j, "anchor": cids[anchor], "family": fam(anchor),
                    "keep": v["keep"], "reasons": "+".join(v["reasons"]),
                    "answer": option_pick(anchor, menu) if kind == "planted" else "nothing found",
                    "ms_pick": option_pick(v["k_ms"], menu), "ho_pick": option_pick(v["k_ho"], menu),
                    "k_ms": cids[v["k_ms"]], "k_ho": cids[v["k_ho"]],
                    "ms_best_option": option_pick(ms_menu, menu),
                    "ms_margin_info": _f(M[anchor] - np.nanmax(M[others])) if kind == "planted"
                    else _f(0.65 - np.nanmax(M[menu])),
                    "margin_A": _f(mg(a["A"])), "margin_C": _f(mg(a["C"])), "margin_F2": _f(mg(a["F2"])),
                    "auroc_C_anchor": _f(a["C"][anchor]), "auroc_F2_anchor": _f(a["F2"][anchor]),
                    "fire_A_anchor": _f(st.fire_A[st.pos[j], anchor]),
                    "fire_F_anchor": _f(st.fire_F[st.pos[j], anchor]),
                    "generic_fire_A": _f(rate[j]), "generic_fire_F": _f(st.gen_fire_F[st.pos[j]])})
        log(f"L{L}: {len(ids)} pooled latents in {time.time() - tl:.0f}s")
        del st, Ms, Hs
    if max_menu_diff > 2e-3:
        raise RuntimeError(f"instance menu_auroc_A differs from recomputed split-A AUROC by {max_menu_diff}")
    slot_rows.sort(key=lambda r: (r["instance_id"], r["slot"]))

    ref_info = reference_by_slot(insts, slot_rows, src_cache, ref_sims) if ref_sims else None

    params = {"rule": "PREREG Amendment 1, A1.1", "thr": thr, "f1_f2_split": "first text per style -> F1",
              "src_cache": src_cache, "src_instances": src_instances, "diag_cache": diag_cache, "git_sha": git_sha(),
              "bank_F_texts_checked_against_files": n_bank_checked,
              "bank_manifest_sha256": sha256_file(os.path.join(diag_cache, "manifest.json"))
              if os.path.exists(os.path.join(diag_cache, "manifest.json")) else None}
    os.makedirs(diag_cache, exist_ok=True)
    np.savez_compressed(os.path.join(diag_cache, "pool_scores.npz"), **npz)
    os.makedirs(logs_dir, exist_ok=True)
    with open(os.path.join(logs_dir, "key_check.jsonl"), "w") as f:
        for r in key_rows:
            f.write(json.dumps(r) + "\n")
    with open(os.path.join(logs_dir, "slot_disagreements.jsonl"), "w") as f:
        for r in slot_rows:
            if not r["keep"]:
                f.write(json.dumps({k: r[k] for k in ("instance_id", "tier", "slot", "kind", "layer", "real_latent",
                                                      "anchor", "reasons", "answer", "ms_pick", "ho_pick", "k_ms",
                                                      "k_ho")}) + "\n")
    write_csv(os.path.join(out_dir, "pool_latents.csv"), pool_rows)
    write_csv(os.path.join(out_dir, "slots.csv"), slot_rows)
    integ["anchor_differs_from_float32_recomputed_argmax_A (near-ties; generator table used)"] = n_a32_reorder
    summary = summarize(slot_rows, pool_rows, params, ref_info, integ, max_menu_diff, T, cids)
    summary["elapsed_s"] = round(time.time() - t0, 1)
    json.dump(summary, open(os.path.join(out_dir, "summary.json"), "w"), indent=1)
    log(f"analyze done in {time.time() - t0:.0f}s -> {out_dir}, {logs_dir}")
    return summary


def reference_by_slot(insts, slot_rows, src_cache, n_seeds):
    """Offline reference solver (simulate.py: split-C probes, the real solve_slot logic) per slot, n_seeds runs.
    Adds ref_acc to each slot row; returns planted accuracy for kept vs dropped slots (PREREG step 2 criterion 3)."""
    use_src_cache(src_cache)
    from tasks.featurematch import simulate
    from tasks.featurematch.grader import grade
    D = simulate.load()
    idx = {(r["instance_id"], r["slot"]): r for r in slot_rows}
    acc = defaultdict(list)
    for d, inst in insts:
        pub = json.load(open(os.path.join(d, "public.json")))
        for sd in range(n_seeds):
            sub, _ = simulate.sim_ref(inst, pub, D, {}, sd)
            g = grade(d, sub)
            for si, sl in enumerate(g["details"]["slots"]):
                acc[(inst["instance_id"], si)].append(bool(sl["correct"]))
    del D
    for k, v in acc.items():
        idx[k]["ref_acc"] = _f(np.mean(v))
    out = {"ref_sims": n_seeds}
    for kind in ("planted", "null"):
        for keep in (True, False):
            vals = [r["ref_acc"] for r in slot_rows if r["kind"] == kind and r["keep"] == keep and "ref_acc" in r]
            out[f"ref_{kind}_acc_{'kept' if keep else 'dropped'}"] = _f(np.mean(vals)) if vals else None
            out[f"n_{kind}_{'kept' if keep else 'dropped'}"] = len(vals)
    k, dr = out["ref_planted_acc_kept"], out["ref_planted_acc_dropped"]
    out["ref_planted_acc_kept_minus_dropped"] = _f(k - dr) if k is not None and dr is not None else None
    return out


def write_csv(p, rows):
    keys = list(rows[0].keys()) if rows else []
    for r in rows:
        for k in r:
            if k not in keys:
                keys.append(k)
    with open(p, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=keys)
        w.writeheader()
        for r in rows:
            w.writerow(r)


def _frac(rows, key):
    return _f(np.mean([bool(r[key]) for r in rows])) if rows else None


def _by(rows, key, fn):
    return {str(v): fn([r for r in rows if r[key] == v]) for v in sorted({r[key] for r in rows}, key=str)}


def summarize(slot_rows, pool_rows, params, ref_info, integ, max_menu_diff, T, cids):
    s = {"params": params,
         "integrity": {"max_abs_diff_splitA_auroc_vs_generator_cache": integ,
                       "max_abs_diff_instance_menu_auroc_A": _f(max_menu_diff, 6)}}
    cnt = lambda rs: {"n": len(rs), "kept": sum(r["keep"] for r in rs), "kept_frac": _frac(rs, "keep")}  # noqa: E731
    p = {**cnt(pool_rows),
         "P31_ms_key_eq_cstar": _frac(pool_rows, "ms_ok"),
         "P31_by_family": _by(pool_rows, "family", lambda rs: _frac(rs, "ms_ok")),
         "P32_ho_key_eq_cstar": _frac(pool_rows, "ho_ok"),
         "P32_by_family": _by(pool_rows, "family", lambda rs: _frac(rs, "ho_ok")),
         "P33_filter_pass (F2>=thr and C>=thr)": _frac(pool_rows, "robust"),
         "P33_by_family": _by(pool_rows, "family", lambda rs: _frac(rs, "robust")),
         "filter_part_F2_pass": _frac(pool_rows, "robust_F2"), "filter_part_C_pass": _frac(pool_rows, "robust_C"),
         "P3_auroc_F_all_bank_F_ge_thr": _frac(pool_rows, "robust_F_all (PREREG auroc_F)"),
         "P3_by_family": _by(pool_rows, "family", lambda rs: _frac(rs, "robust_F_all (PREREG auroc_F)")),
         "P35_dropped_only_for_key_disagreement": _f(np.mean([(not r["keep"]) and r["robust"] for r in pool_rows])),
         "P35_n": sum(1 for r in pool_rows if (not r["keep"]) and r["robust"]),
         "ties_ms": sum(r["tie_ms"] for r in pool_rows), "ties_ho": sum(r["tie_ho"] for r in pool_rows),
         "reasons": dict(Counter(r["reasons"] or "kept" for r in pool_rows).most_common()),
         "reason_any": {k: sum(k in r["reasons"].split("+") for r in pool_rows)
                        for k in ("ms_key_differs", "heldout_key_differs", "not_style_robust")},
         "by_layer": _by(pool_rows, "layer", cnt), "by_family": _by(pool_rows, "family", cnt),
         "by_layer_family": {f"L{L}_{fm}": cnt([r for r in pool_rows if r["layer"] == L and r["family"] == fm])
                             for L in LAYERS for fm in sorted({r["family"] for r in pool_rows})},
         "concepts_with_kept_latent": {}}
    for L in LAYERS:
        rs = [r for r in pool_rows if r["layer"] == L]
        p["concepts_with_kept_latent"][f"L{L}"] = {
            "answerable_before": len({r["anchor"] for r in rs}),
            "with_kept_latent": len({r["anchor"] for r in rs if r["keep"]}),
            "by_family": {fm: len({r["anchor"] for r in rs if r["keep"] and r["family"] == fm})
                          for fm in sorted({r["family"] for r in rs})}}
    s["pool"] = p
    sl = {"n": len(slot_rows), "failed": sum(not r["keep"] for r in slot_rows),
          "P36_fail_frac": _f(np.mean([not r["keep"] for r in slot_rows]))}
    for kind in ("planted", "null"):
        rs = [r for r in slot_rows if r["kind"] == kind]
        if not rs:
            continue
        fail = lambda x: {"n": len(x), "failed": sum(not r["keep"] for r in x),             # noqa: E731
                          "fail_frac": _f(np.mean([not r["keep"] for r in x])) if x else None}
        sl[kind] = {**fail(rs), "reasons": dict(Counter(r["reasons"] or "kept" for r in rs).most_common()),
                    "by_layer": _by(rs, "layer", fail), "by_family": _by(rs, "family", fail),
                    "by_tier": _by(rs, "tier", fail)}
        if kind == "planted":
            sl[kind]["ms_pick_not_answer"] = sum(r["ms_pick"] != r["answer"] for r in rs)
            sl[kind]["ho_pick_not_answer"] = sum(r["ho_pick"] != r["answer"] for r in rs)
            sl[kind]["ms_pick_not_on_menu"] = sum(r["ms_pick"] == "not on menu" for r in rs)
            sl[kind]["ms_best_option_not_answer"] = sum(r["ms_best_option"] != r["answer"] for r in rs)
        else:
            sl[kind]["ms_key_on_menu"] = sum(r["ms_pick"] != "not on menu" for r in rs)
            sl[kind]["ho_key_on_menu"] = sum(r["ho_pick"] != "not on menu" for r in rs)
    by_inst = defaultdict(list)
    for r in slot_rows:
        by_inst[r["instance_id"]].append(r["keep"])
    sl["instances"] = len(by_inst)
    sl["instances_all_slots_kept"] = sum(all(v) for v in by_inst.values())
    s["slots_v2"] = sl
    feats_pool = ["generic_fire_A", "generic_fire_F", "fire_A_anchor", "fire_F_anchor", "margin_A", "margin_B",
                  "margin_C", "auroc_A_anchor", "auroc_B_anchor", "auroc_C_anchor", "auroc_F2_anchor"]
    s["pool_kept_vs_dropped"] = compare(pool_rows, feats=feats_pool)
    s["reference_offline_v2_slots"] = ref_info
    s["filter_selects_easier_PRIMARY_latents"] = easier_verdict(s["pool_kept_vs_dropped"], ref_info)
    s["slots_kept_vs_dropped"] = compare(slot_rows, feats=["generic_fire_A", "generic_fire_F", "fire_A_anchor",
                                                          "fire_F_anchor", "margin_A", "margin_C", "margin_F2"])
    s["filter_selects_easier_secondary_v2_slots"] = easier_verdict(s["slots_kept_vs_dropped"], ref_info)
    return s


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="mode", required=True)
    c = sub.add_parser("compute", help="GPU: bank-F/R activations (run under common.gpuq)")
    c.add_argument("--dry-run", action="store_true", help="CPU, 2 concepts, 1 layer, output under cache/dryrun/")
    c.add_argument("--layers", default="", help="comma list (default 6,12,18; dry-run: first given or 12)")
    c.add_argument("--banks", default="F,R")
    c.add_argument("--batch", type=int, default=BATCH)
    c.add_argument("--device", default=None)
    c.add_argument("--src-cache", default=None)
    c.add_argument("--banks-dir", default=BANKS)
    c.add_argument("--out-dir", default=None)
    c.add_argument("--consistency-n", type=int, default=None)
    z = sub.add_parser("analyze", help="CPU: PREREG A1.1 per-latent keep rule, logs, comparison")
    z.add_argument("--src-cache", default=None)
    z.add_argument("--src-instances", default=None)
    z.add_argument("--diag-cache", default=DIAG_CACHE)
    z.add_argument("--banks-dir", default=BANKS)
    z.add_argument("--out-dir", default=OUT)
    z.add_argument("--logs-dir", default=HERE, help="where key_check.jsonl / slot_disagreements.jsonl go")
    z.add_argument("--thr", type=float, default=THR)
    z.add_argument("--ref-sims", type=int, default=1, help="offline reference runs per v2 instance (0 = skip)")
    a = ap.parse_args()
    if a.mode == "compute":
        run_compute(a)
    else:
        s = analyze(a.src_cache, a.src_instances, a.diag_cache, a.out_dir, a.thr, a.ref_sims, a.banks_dir,
                    a.logs_dir)
        print(json.dumps({"pool": {k: s["pool"][k] for k in ("n", "kept", "kept_frac", "by_layer", "by_family")},
                          "slots_v2": {k: s["slots_v2"][k] for k in ("n", "failed", "P36_fail_frac")},
                          "easier": s["filter_selects_easier_PRIMARY_latents"]}, indent=1))


if __name__ == "__main__":
    main()
