"""Regenerate the style-filtered FeatureMatch pool ("v2f") from the kept latents (CPU; run after style_filter analyze).

PREREG Amendment 1, A1.1 + step 2 (binding): the keep rule acts on POOLED LATENTS (style_filter.verdict; the same rule
for planted and null use). The filtered pool is then REGENERATED by generator v2, unchanged otherwise, from the kept
latents only: generate.Tables with its latent pool restricted to the kept latents (so the anchor draw, the per-layer
menu universe "concepts that own a pooled latent at this layer", the confusable-set exclusion, the menu construction,
the null pattern and the ids are all generator v2's own code), then generate.make_instance for 60 instances per tier
on seeds 8000+ (T1), 108000+ (T2), 208000+ (T3) (= start_seed + 100000 x tier index, as generate.main).

Checks per written instance: the generator's own asserts; every menu has 20 options; every slot latent is kept;
planted slots whose multi-style best option (argmax M over the menu) is not the answer are counted (expected 0, and the
run fails otherwise); the public/privileged consistency check (verify). Diagnostics only (no slot is dropped for
them): the multi-style margin per slot (planted: M(answer) - best other option's M; null: 0.65 - best option's M) and
null slots where some option passes the robustness bar (AUROC_F2 >= 0.85 and AUROC_C >= 0.85).
Feasibility is reported BEFORE drawing: kept latents per layer x family, concepts with a kept latent per layer, and
kept latents whose menu universe minus their confusable set is too small for a 20-option menu. If an instance cannot
be produced the error is recorded per tier and the run exits non-zero after writing the summary (no rule is loosened).

Fingerprint check (PREREG P6): fingerprint_check.feats (public menu structure + layer) with the same 5-fold
cross-validated gradient-boosted classifier, (a) on the regenerated pool's slots and (b) on in-memory instances of the
filtered generator, seeds 500000+ (never written), as fingerprint_check.main does; plus a latent-only check
(layer + generic fire rate) and the one-feature density check (generic fire rate, null vs planted).

Run: $PY -m tasks.featurematch.diagnosis.write_v2f [--clean]
Out: tasks/featurematch/instances_v2f/<id>/{instance.json,public.json} (gitignored),
     diagnosis/instances_v2f_manifest.json, diagnosis/style_filter_out/v2f_summary.json
"""
import argparse
import hashlib
import json
import os
import shutil
import sys
from collections import Counter

import numpy as np

from tasks.featurematch.diagnosis import style_filter as SF
from tasks.featurematch.fm_core import LAYERS

OUT_INST = os.path.join(SF.TASK, "instances_v2f")
MANIFEST = os.path.join(SF.HERE, "instances_v2f_manifest.json")
FILTER_VERSION = "v2f-A1.1"


class PoolScores:
    """M, H, AUROC_C, AUROC_F2 rows (over all concepts) of every pooled latent (style_filter analyze output)."""

    def __init__(self, path):
        z = np.load(path)
        self.rows = {}
        for L in LAYERS:
            if f"L{L}_latents" not in z:
                continue
            arrs = {k: z[f"L{L}_{k}"] for k in ("M", "H", "C", "F2")}
            for i, j in enumerate(z[f"L{L}_latents"]):
                self.rows[(L, int(j))] = {k: v[i] for k, v in arrs.items()}

    def get(self, L, j):
        return self.rows[(int(L), int(j))]


def load_kept(key_check):
    kept, n = set(), 0
    for line in open(key_check):
        r = json.loads(line)
        n += 1
        if r["kept"]:
            kept.add((int(r["layer"]), int(r["real_latent"])))
    return kept, n


def restrict_tables(T, kept):
    """Generator v2's Tables with the latent pool restricted to the kept latents; everything downstream of the pool
    (planted_by_c, the per-layer answerable set = menu universe) is rebuilt exactly as Tables.pools builds it."""
    for L in LAYERS:
        T.planted[L] = [(j, c) for j, c in T.planted[L] if (L, j) in kept]
        byc = {}
        for j, c in T.planted[L]:
            byc.setdefault(c, []).append(j)
        T.planted_by_c[L] = byc
        T.answerable[L] = np.array(sorted(byc), dtype=np.int64)
        T.pool_stats[L]["kept_A1.1"] = len(T.planted[L])
        T.pool_stats[L]["answerable_concepts_A1.1"] = len(byc)
    return T


def feasibility(T):
    """Before drawing: can every kept latent get a 20-option menu from its layer's universe minus its confusables?"""
    from tasks.featurematch.generate import N_OPT, N_THR, N_THR_B
    out = {}
    for L in LAYERS:
        ans = set(int(c) for c in T.answerable[L])
        fams = Counter(T.cs[c]["cid"].split(":")[0] for c in ans)
        short_p, short_n, cand = 0, 0, []
        for j, c in T.planted[L]:
            excl = set(np.nonzero((T.aA[L][j] >= N_THR) | (T.aB[L][j] >= N_THR_B))[0].tolist()) | {c}
            n = len(ans - excl)
            cand.append(n)
            short_p += n < N_OPT - 1
            short_n += n < N_OPT
        out[f"L{L}"] = {"kept_latents": len(T.planted[L]),
                        "kept_latents_by_family": dict(Counter(T.cs[c]["cid"].split(":")[0] for _, c in T.planted[L])),
                        "concepts_with_kept_latent": len(ans), "concepts_by_family": dict(fams),
                        "menu_candidates_min": int(min(cand)) if cand else None,
                        "menu_candidates_median": float(np.median(cand)) if cand else None,
                        "latents_too_few_candidates_planted(<19)": int(short_p),
                        "latents_too_few_candidates_null(<20)": int(short_n)}
    return out


def build_sources(tiers, n_per_tier, start_seed):
    from tasks.featurematch.generate import TIERS
    return [(tier, start_seed + 100000 * sorted(TIERS).index(tier) + k) for tier in tiers for k in range(n_per_tier)]


def slot_checks(T, PS, inst):
    """Per slot: planted multi-style best option == answer (violation count), multi-style margin (info), null option
    passing the robustness bar (info)."""
    cid2i = {c["cid"]: i for i, c in enumerate(T.cs)}
    viol, margins, null_rival = 0, [], []
    for s in inst["extra"]["slots"]:
        sc = PS.get(s["layer"], s["real_latent"])
        M = np.where(np.isfinite(sc["M"]), sc["M"], -np.inf)
        menu = [cid2i[c] for c in s["menu"]]
        a = cid2i[s["anchor"]]
        if s["kind"] == "planted":
            best = menu[int(np.argmax(M[menu]))]
            viol += int(best != a or int(np.argmax(M)) != a)
            margins.append(round(float(M[a] - max(M[c] for c in menu if c != a)), 4))
            null_rival.append(None)
        else:
            margins.append(round(float(0.65 - M[menu].max()), 4))
            null_rival.append(bool(any(sc["F2"][c] >= SF.THR and sc["C"][c] >= SF.THR for c in menu)))
    return viol, margins, null_rival


def verify(T, d, inst, public):
    """Re-derive what the tool server and grader read and check it is consistent."""
    from tasks.featurematch.tools import perm_for
    assert inst["canary"] == "RLCANARY-featurematch-" + hashlib.sha256(
        f"canary-{inst['instance_id']}".encode()).hexdigest()[:16]
    assert os.path.basename(d) == inst["instance_id"]
    for ps, s, a in zip(public["slots"], inst["extra"]["slots"], inst["answer"]["slots"]):
        assert perm_for(inst["extra"]["perm_seed"], ps["layer"])[ps["latent"]] == s["real_latent"]
        assert ps["layer"] == s["layer"] and len(ps["options"]) == len(s["menu"]) == 20
        if s["kind"] == "planted":
            assert a["planted"] and a["concept"] == s["anchor"]
            lab = next(c["label"] for c in T.cs if c["cid"] == s["anchor"])
            assert ps["options"][a["choice"] - 1] == lab
        else:
            assert not a["planted"] and a["choice"] == "nothing found" and s["anchor"] not in s["menu"]
    assert public["n_slots"] == len(public["slots"]) == len(inst["answer"]["slots"])
    pub_txt = json.dumps(public)
    assert inst["canary"] not in pub_txt and not any(x in pub_txt for x in inst["leak_strings"])


def density_auroc(slots_by_kind, rate):
    """Single-feature fingerprint check: AUROC of 'generic fire rate' for predicting null vs planted (0.5 = none)."""
    from tasks.featurematch.reference_solver import auroc
    x = {k: [float(rate[L][j]) for L, j in v] for k, v in slots_by_kind.items()}
    if not x.get("null") or not x.get("planted"):
        return None
    return round(auroc(x["null"], x["planted"]), 4)


def _cv_auroc(X, y):
    from sklearn.ensemble import GradientBoostingClassifier
    from sklearn.model_selection import cross_val_score
    X, y = np.array(X, dtype=float), np.array(y, dtype=int)
    if len(set(y.tolist())) < 2 or min(np.bincount(y)) < 5:
        return {"n_slots": int(len(y)), "cv_auroc": None}
    auc = cross_val_score(GradientBoostingClassifier(random_state=0), X, y, cv=5, scoring="roc_auc")
    return {"n_slots": int(len(y)), "null_frac": round(float(1 - y.mean()), 3), "cv_auroc": round(float(auc.mean()), 3),
            "cv_auroc_sd": round(float(auc.std()), 3)}


def fingerprint(T, insts_by_tier, n_mem):
    """PREREG P6: public-feature fingerprint (fingerprint_check.feats) on (a) the written pool and (b) n_mem in-memory
    instances per tier of the filtered generator (seeds 500000+, as fingerprint_check.main); plus a latent-only check
    (layer + generic fire rate) and the one-feature density AUROC."""
    from tasks.featurematch.fingerprint_check import feats
    from tasks.featurematch.generate import TIERS, make_instance
    lab2c = {c["label"]: i for i, c in enumerate(T.cs)}
    out = {"written_pool": {}, "generator_in_memory": {}, "rule": "CV AUROC <= 0.6 for null vs planted"}

    def collect(pairs):
        X, Xl, y, kinds = [], [], [], {"planted": [], "null": []}
        for inst, pub in pairs:
            for s, ans, priv in zip(pub["slots"], inst["answer"]["slots"], inst["extra"]["slots"]):
                X.append(feats(T, s["layer"], s["options"], lab2c))
                Xl.append([s["layer"], float(T.rate[s["layer"]][priv["real_latent"]])])
                y.append(int(ans["planted"]))
                kinds["planted" if ans["planted"] else "null"].append((s["layer"], priv["real_latent"]))
        return X, Xl, y, kinds

    def block(pairs):
        X, Xl, y, kinds = collect(pairs)
        return {"menu_features": _cv_auroc(X, y), "latent_features": _cv_auroc(Xl, y),
                "density_auroc": density_auroc(kinds, T.rate)}

    allp = []
    for tier, pairs in sorted(insts_by_tier.items()):
        allp += pairs
        out["written_pool"][tier] = block(pairs)
    out["written_pool"]["all"] = block(allp)
    for tier in TIERS:
        pairs, fails = [], 0
        for k in range(n_mem):
            try:
                _, inst, pub = make_instance(T, 500000 + k, tier)
            except Exception:
                fails += 1
                continue
            pairs.append((inst, pub))
        out["generator_in_memory"][tier] = {"n_instances": len(pairs), "failed_draws": fails, **block(pairs)}
    vals = [v[k]["cv_auroc"] for grp in ("written_pool", "generator_in_memory") for v in out[grp].values()
            for k in ("menu_features", "latent_features") if v[k].get("cv_auroc") is not None]
    out["max_cv_auroc"] = max(vals) if vals else None
    out["passes"] = bool(vals) and max(vals) <= 0.6
    return out


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--key-check", default=os.path.join(SF.HERE, "key_check.jsonl"))
    ap.add_argument("--pool-scores", default=os.path.join(SF.DIAG_CACHE, "pool_scores.npz"))
    ap.add_argument("--src-cache", default=None)
    ap.add_argument("--out-instances", default=OUT_INST)
    ap.add_argument("--manifest", default=MANIFEST)
    ap.add_argument("--summary", default=os.path.join(SF.OUT, "v2f_summary.json"))
    ap.add_argument("--mode", choices=("regenerate",), default="regenerate",
                    help="only mode (PREREG step 2 / A1.1); the pre-A1.1 redraw/drop modes were removed")
    ap.add_argument("--n-per-tier", type=int, default=60)
    ap.add_argument("--start-seed", type=int, default=8000, help="PREREG: 8000 / 108000 / 208000")
    ap.add_argument("--tiers", default="T1,T2,T3")
    ap.add_argument("--fingerprint-n", type=int, default=600, help="in-memory instances per tier (0 = skip)")
    ap.add_argument("--clean", action="store_true")
    a = ap.parse_args(argv)
    from tasks.featurematch.generate import GEN_VERSION, make_instance
    src_cache = a.src_cache or SF.default_src_cache()
    T = SF.load_tables(src_cache)
    kept, n_pool = load_kept(a.key_check)
    pool_before = {L: len(T.planted[L]) for L in LAYERS}
    if sum(pool_before.values()) != n_pool:
        raise RuntimeError(f"key_check.jsonl has {n_pool} latents, generator pool {sum(pool_before.values())}")
    restrict_tables(T, kept)
    PS = PoolScores(a.pool_scores)
    feas = feasibility(T)
    if a.clean and os.path.exists(a.out_instances):
        shutil.rmtree(a.out_instances)
    os.makedirs(a.out_instances, exist_ok=True)
    man, errors, viol_total = [], {}, 0
    by_tier = {}
    margins = {"planted": [], "null": []}
    null_rival, slot_counts, null_n, slot_n = 0, Counter(), 0, 0
    fam_anchor, layer_mix, used_lat, used_anchor = Counter(), Counter(), set(), set()
    for tier, seed in build_sources(a.tiers.split(","), a.n_per_tier, a.start_seed):
        try:
            iid, inst, public = make_instance(T, seed, tier)
            for s in inst["extra"]["slots"]:
                if len(s["menu"]) != 20:
                    raise RuntimeError(f"menu has {len(s['menu'])} options (menu universe too small)")
                if (s["layer"], s["real_latent"]) not in kept:
                    raise RuntimeError("slot latent not kept")
        except Exception as e:           # recorded and reported, never patched
            errors.setdefault(tier, []).append({"seed": seed, "error": f"{type(e).__name__}: {e}"})
            continue
        v, mg, nr = slot_checks(T, PS, inst)
        viol_total += v
        inst["extra"]["style_filter"] = {"version": FILTER_VERSION, "rule": "PREREG A1.1 (latent keep rule)",
                                         "ms_margin_info": mg, "null_option_passes_robustness_info": nr}
        od = os.path.join(a.out_instances, iid)
        if os.path.exists(od):
            raise RuntimeError(f"instance id collision: {iid}")
        os.makedirs(od)
        json.dump(inst, open(os.path.join(od, "instance.json"), "w"), indent=1)
        json.dump(public, open(os.path.join(od, "public.json"), "w"), indent=1)
        verify(T, od, inst, public)
        by_tier.setdefault(tier, []).append((inst, public))
        slot_counts[len(inst["extra"]["slots"])] += 1
        for s, m, r in zip(inst["extra"]["slots"], mg, nr):
            k = "planted" if s["kind"] == "planted" else "null"
            margins[k].append(m)
            null_rival += bool(r)
            null_n += k == "null"
            slot_n += 1
            fam_anchor[(k, s["anchor"].split(":")[0])] += 1
            layer_mix[s["layer"]] += 1
            used_lat.add((s["layer"], s["real_latent"]))
            used_anchor.add(s["anchor"])
        man.append({"instance_id": iid, "tier": tier, "seed": seed, "dial": inst["dial"],
                    "files": {f: SF.sha256_file(os.path.join(od, f)) for f in ("instance.json", "public.json")}})
    summ = {
        "mode": "regenerate", "rule": "PREREG A1.1", "filter_version": FILTER_VERSION,
        "pool_before": {f"L{L}": pool_before[L] for L in LAYERS}, "pool_kept": len(kept),
        "feasibility": feas,
        "instances_written_by_tier": {t: len(v) for t, v in sorted(by_tier.items())},
        "instances_requested_per_tier": a.n_per_tier,
        "errors_by_tier": {t: {"n": len(v), "examples": v[:5]} for t, v in errors.items()},
        "slot_count_dist": dict(sorted(slot_counts.items())),
        "n_slots": slot_n, "null_fraction": SF._f(null_n / max(1, slot_n)),
        "all_null_episodes": sum(1 for pairs in by_tier.values() for i, _ in pairs if not i["planted"]),
        "layer_mix": {str(k): v for k, v in sorted(layer_mix.items())},
        "anchor_family_by_kind": {f"{k}_{f}": n for (k, f), n in sorted(fam_anchor.items())},
        "planted_ms_key_not_answer (expected 0)": viol_total,
        "ms_margin_info": {k: SF.describe(v) for k, v in margins.items()},
        "null_slots_with_option_passing_robustness_info": null_rival,
        "distinct_kept_latents_used": len(used_lat), "distinct_anchor_concepts_used": len(used_anchor),
    }
    if a.fingerprint_n and by_tier:
        summ["fingerprint_P6"] = fingerprint(T, by_tier, a.fingerprint_n)
    cv = os.path.join(src_cache, "concepts_validation.json")
    json.dump({"generator": "tasks/featurematch/generate.py (v2, pool restricted to A1.1-kept latents) via "
                            "tasks/featurematch/diagnosis/write_v2f.py",
               "filter_version": FILTER_VERSION, "gen_version": GEN_VERSION, "mode": "regenerate",
               "key_check_sha256": SF.sha256_file(a.key_check),
               "concepts_sha256": json.load(open(cv))["sha256"] if os.path.exists(cv) else None,
               "instances": man}, open(a.manifest, "w"), indent=1)
    os.makedirs(os.path.dirname(a.summary), exist_ok=True)
    json.dump(summ, open(a.summary, "w"), indent=1)
    print(json.dumps(summ, indent=1))
    if viol_total:
        raise RuntimeError(f"{viol_total} planted slots whose multi-style key is not the answer")
    if errors:
        print(f"REGENERATION INCOMPLETE: {sum(len(v) for v in errors.values())} instances could not be produced",
              file=sys.stderr)
        if argv is None:
            sys.exit(2)
    return summ


if __name__ == "__main__":
    main()
